# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DeliveryList' do

  use_frameworks!
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'PKHUD'

end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
